[package]
name = "account-sample"
version = "0.1.0"
authors = ["Mark bskin0330@gmail.com"]
publish = false

[dependencies]
elastic = "~0.21.0-pre.5"
elastic_derive = "~0.21.0-pre.5"
quick-error = "~1"
serde = "~1"
serde_json = "~1"
serde_derive = "~1"
